package com.soja.Persistor.dto;

public class GeneratedTweetDto {

    private int id;
    private String tweetText;
    private boolean wasPublished;
    private boolean wasAutogenerated;

    public GeneratedTweetDto(int id, String tweetText, boolean wasPublished, boolean wasAutogenerated) {
        this.id = id;
        this.tweetText = tweetText;
        this.wasPublished = wasPublished;
        this.wasAutogenerated = wasAutogenerated;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTweetText() {
        return tweetText;
    }

    public void setTweetText(String tweetText) {
        this.tweetText = tweetText;
    }

    public boolean getWasPublished() {
        return wasPublished;
    }

    public void setWasPublished(boolean wasPublished) {
        this.wasPublished = wasPublished;
    }

    public boolean getWasAutogenerated() {
        return wasAutogenerated;
    }

    public void setWasAutogenerated(boolean wasAutogenerated) {
        this.wasAutogenerated = wasAutogenerated;
    }
}
