package com.soja.Persistor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "GENERATED_TWEETS")
public class GeneratedTweet {

    private int id;
    private String tweetText;
    private boolean wasPublished;
    private boolean wasAutogenerated;

    public GeneratedTweet() {
    }

    public GeneratedTweet(int id, String tweetText, boolean wasPublished, boolean wasAutogenerated) {
        this.id = id;
        this.tweetText = tweetText;
        this.wasPublished = wasPublished;
        this.wasAutogenerated = wasAutogenerated;
    }

    @Id
    @GeneratedValue
    @NotNull
    @Column(name = "ID", unique = true)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "TWWET_TEXT")
    public String getTweetText() {
        return tweetText;
    }

    public void setTweetText(String tweetText) {
        this.tweetText = tweetText;
    }

    @Column(name = "PUBLISHED")
    public boolean getWasPublished() {
        return wasPublished;
    }

    public void setWasPublished(boolean wasPublished) {
        this.wasPublished = wasPublished;
    }

    @Column(name = "AUTOGENERATED")
    public boolean getWasAutogenerated() {
        return wasAutogenerated;
    }

    public void setWasAutogenerated(boolean wasAutogenerated) {
        this.wasAutogenerated = wasAutogenerated;
    }
}
